name: ap-env
channels:
  - fenics
  - conda-forge
  - cadquery
  - defaults
dependencies:
  - python==3.12.10
  - numpy=2.2.4
  - numba=0.61.2
  - matplotlib=3.10.1
  - scipy=1.15.2
  - h5py=3.13.0
  - tqdm=4.67.1
  - pandas=2.2.3
  - pkg-config=0.29.2

prefix: /opt/anaconda3/envs/ap-env
